[project]
name = "sparsity"
version = "0.1.0"
description = "Sparsity Visualization"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "marimo[recommended]>=0.23.10",
    "numpy>=2.5.0",
    "plotly>=6.8.0",
]

[dependency-groups]
dev = [
  "ty>=0.0.51",
  "pydantic>=2",
  "pytest>=9.1.1",
  "python-lsp-ruff>=2.3.1",
  "python-lsp-server>=1.14.0",
  "websockets>=16.0",
]
